### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by arpainter** [alphagov/prototype-kit-training#65]
### What did you do? (steps to reproduce)

https://prototype-kit-training.cloudapps.digital/task-2.html#task-2-adding-questions-to-your-pages

Followed link - "Follow the tutorial on how to add questions to your question pages."

### What happened? (actual results)

Destination page not found - https://govuk-prototype-kit.herokuapp.com/docs/make-first-prototype/add-questions

### What should have happened? (expected results)

Page found and content loaded

**Comment by 36degrees** [comment]
Thanks for reporting this, @arpainter. The broken link now redirects because of the changes in https://github.com/alphagov/govuk-prototype-kit/pull/1033.

I've raised a further pull request to avoid the unnecessary redirect and make the link text clearer.
