### ISSUE TITLE
Prepare for transition to the Prototype Kit site

### ISSUE THREAD

**Issue by joelanman** [alphagov/prototype-kit-training#73]
We are moving all missing content to the [Prototype Kit site](https://govuk-prototype-kit.herokuapp.com/docs)

When that is done, we'll need to turn this site off and redirect all the pages.

### Tasks
- [x] investigate where and how the training site is hosted and deployed
- [x] create redirects
- [x] deploy redirects to replace the training site

**Comment by lfdebrux** [comment]
Done in https://github.com/alphagov/govuk-prototype-kit/issues/1275.
